# The URL the site will be built for
base_url = "https://uncomfyhalomacro.codeberg.page"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

theme = "jera"

generate_feed = true

ignored_content = ["*/**/*.zk/*"]

taxonomies = [
  {name = "tags", render = true, feed = true}
]



[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true

render_emoji = true

extra_syntaxes_and_themes = ["static/assets/highlighting/catppuccin"]

highlight_theme = "css"

highlight_themes_css = [
  { theme = "Catppuccin-mocha", filename = "syntax-theme-dark.css" },
  { theme = "Catppuccin-latte", filename = "syntax-theme-light.css" },
]

[extra]
# Put all your custom variables here

theme_color = "auto"

author = "uncomfyhalomacro"

masto_url = "julialang.social"

masto_username = "uncomfyhalomacro"

twitter_username = "uncomfyhalo"

show_masto_social = true

more_sections = [
  { name="notes" },
  { name="lecture" }
]


